const rows = [
  ["data-convert", "format", "数据格式转换", "Data format converter", "data-convert", ["json-convert", "yaml", "csv", "tsv", "ndjson", "xml", "toml", "json", "yaml-json", "csv-json", "xml-json", "toml-json", "数据转换", "双向转换"]],
  ["spreadsheet", "format", "表格工具", "Spreadsheet tools", "spreadsheet", ["xlsx", "excel", "csv编辑", "tsv", "表格编辑", "excel转json", "json转excel", "工作表"]],
  ["image-process", "image", "图片处理", "Image tools", "image-process", ["图片压缩", "裁剪", "缩放", "旋转", "翻转", "水印", "格式转换", "jpeg", "png", "webp"]],
  ["jsonpath", "format", "JSONPath 提取", "JSONPath", "jsonpath"],
  ["base-convert", "convert", "进制转换", "Number base", "base-convert"],
  ["network-calc", "convert", "IPv4 / IPv6 / CIDR 计算", "IPv4 / IPv6 / CIDR calculator", "network-calc", ["ip", "ipv4", "ipv6", "cidr", "子网", "子网切分", "子网掩码", "广播地址", "网络地址", "ip转整数"]],
  ["timestamp", "convert", "Unix 时间戳互转", "Unix timestamp converter", "time-convert", ["duration", "unix", "timestamp", "time", "beijing", "epoch"]],
  ["color", "convert", "颜色转换", "Color convert", "color-convert", ["hex", "rgb", "hsl", "hsv", "cmyk", "colour", "eyedropper", "picker"]],
  ["cron", "convert", "Cron 生成与解析", "Cron builder & parser", "cron"],
  ["sql-escape", "encode", "SQL 字符串转义", "SQL string escape", "live-io", ["sql", "in", "quote"]],
  ["base64", "encode", "Base / Hex 编码", "Base / Hex", "base64", ["base32", "base58", "hex"]],
  ["url", "encode", "URL", "URL", "url"],
  ["html-entities", "encode", "文本转义", "Text escape", "html-entities", ["unicode", "html-entities"]],
  ["punycode", "encode", "Punycode", "Punycode", "punycode"],
  ["data-uri", "encode", "Data URI", "Data URI", "data-uri"],
  ["quoted-printable", "encode", "Quoted-printable", "Quoted-printable", "live-io"],
  ["jwt", "security", "JWT", "JWT", "jwt"],
  ["aes", "security", "对称加密", "Symmetric cipher", "aes", ["sm4", "aes", "gcm", "cbc", "iv", "nonce", "aad"]],
  ["hmac-sha256", "security", "HMAC", "HMAC", "hmac", ["hmac-sm3", "hmac"]],
  ["xor", "security", "XOR（仅调试）", "XOR (debug only)", "xor"],
  ["rsa", "security", "非对称加密", "Asymmetric cipher", "rsa", ["sm2", "rsa"]],
  ["jwk", "security", "JWK / JWKS 互操作", "JWK / JWKS interop", "jwk", ["jwk", "jwks", "json web key", "JSON Web Key"]],
  ["cert", "security", "证书 / SSH 指纹", "Cert / SSH fingerprint", "cert", ["ssh-fingerprint"]],
  ["json", "format", "JSON 工作台", "JSON workbench", "json-workbench", [
    "json-convert", "json-yaml", "json-csv", "json-xml", "json-toml", "json-sql", "json-ts",
    "yaml", "csv", "xml", "toml", "sql", "typescript", "python", "go", "java",
    "format", "minify", "validate", "tree", "unicode", "escape", "sort",
    "行号", "树形", "压缩", "转义", "校验", "转换", "语言",
  ]],
  ["code-format", "format", "代码格式化", "Code format", "code-format", ["sql", "xml", "yaml", "html", "css", "javascript", "typescript", "js", "ts", "jsx", "tsx", "validate", "beautify"]],
  ["hash", "security", "哈希与校验", "Hash & checksum", "hash", ["hash", "md5", "sha", "sm3", "crc32", "checksum"]],
  ["uuid", "generate", "唯一 ID", "Unique ID", "unique-id", ["ulid", "nanoid"]],
  ["password", "generate", "随机密码 / 字节", "Random password / bytes", "password", ["random-bytes"]],
  ["symmetric-key", "security", "对称密钥", "Symmetric key", "symmetric-key", ["aes-key", "hmac-key", "生成密钥"]],
  ["key-pair", "security", "非对称密钥", "Asymmetric key", "keypair", ["keypair", "rsa", "sm2", "生成密钥对"]],
  ["qrcode", "generate", "二维码与二维条码", "QR & 2D barcodes", "qrcode", ["qr", "barcode", "汉信", "pdf417", "data matrix", "svg", "批量识别"]],
  ["lorem", "generate", "重复文本 / Lorem", "Repeated text / Lorem", "lorem", ["ipsum", "placeholder", "dbx", "推广文案", "自定义内容"]],
  ["totp", "security", "TOTP 口令", "TOTP", "totp"],
  ["whitespace", "text", "文本处理", "Text tools", "whitespace", ["空白与行", "查找替换", "全半角", "去重", "排序", "前缀", "后缀", "去空行", "大小写", "命名", "序号", "流水号", "随机打乱", "按列截取", "长度过滤", "case", "naming", "字数统计", "stats", "word count", "slugify", "去 HTML 标签", "strip-html", "trim", "unique", "sort", "replace", "camel", "snake", "kebab"]],
  ["regex", "text", "Regex 测试", "Regex tester", "regex"],
  ["diff", "text", "文本 Diff", "Text diff", "diff"],
  ["markdown", "text", "Markdown 预览", "Markdown preview", "markdown"],
  ["unicode-inspect", "text", "Unicode 码位检查器", "Unicode inspector", "unicode-inspect"],
];

export const TOOL_DEFS = rows.map(([id, category, zh, en, view, aliases]) => ({
  id,
  category,
  name: { zh, en },
  view,
  ...(aliases ? { aliases } : {}),
}));
