[package]
name = "dbx-plugin-toolbox"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace]

[dependencies]
aes = "0.8"
aes-gcm = "0.10"
argon2 = "0.5"
base64 = "0.22"
cbc = "0.1"
cipher = { version = "0.4", features = ["alloc", "block-padding"] }
crc32fast = "1"
dbx-plugin-sdk = { version = "0.1.0" }
dirs = "5"
ecb = "0.1"
hex = "0.4"
hmac = "0.12"
md-5 = "0.10"
pem = "3"
rand = "0.8"
rsa = { version = "0.9", features = ["pem"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1 = "0.10"
sha2 = { version = "0.10", features = ["oid"] }
sm3 = "0.4"
sm4 = "0.5"
smcrypto = "0.3.1"
uuid = { version = "1", features = ["v4"] }
rfd = "0.15"
x509-parser = "0.16"
zeroize = { version = "1", features = ["derive"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
